/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnswerRouteImport } from './routes/answer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as AlertIdRouteImport } from './routes/alert.$id'
import { Route as ApiPublicSweepEventsRouteImport } from './routes/api/public/sweep-events'
import { Route as ApiPublicRefreshEventsRouteImport } from './routes/api/public/refresh-events'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerRoute = AnswerRouteImport.update({
  id: '/answer',
  path: '/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertIdRoute = AlertIdRouteImport.update({
  id: '/alert/$id',
  path: '/alert/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSweepEventsRoute = ApiPublicSweepEventsRouteImport.update({
  id: '/api/public/sweep-events',
  path: '/api/public/sweep-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshEventsRoute = ApiPublicRefreshEventsRouteImport.update({
  id: '/api/public/refresh-events',
  path: '/api/public/refresh-events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/alert/$id': typeof AlertIdRoute
  '/event/$id': typeof EventIdRoute
  '/api/public/refresh-events': typeof ApiPublicRefreshEventsRoute
  '/api/public/sweep-events': typeof ApiPublicSweepEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/alert/$id': typeof AlertIdRoute
  '/event/$id': typeof EventIdRoute
  '/api/public/refresh-events': typeof ApiPublicRefreshEventsRoute
  '/api/public/sweep-events': typeof ApiPublicSweepEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/alert/$id': typeof AlertIdRoute
  '/event/$id': typeof EventIdRoute
  '/api/public/refresh-events': typeof ApiPublicRefreshEventsRoute
  '/api/public/sweep-events': typeof ApiPublicSweepEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/answer'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/reset-password'
    | '/settings'
    | '/alert/$id'
    | '/event/$id'
    | '/api/public/refresh-events'
    | '/api/public/sweep-events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/answer'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/reset-password'
    | '/settings'
    | '/alert/$id'
    | '/event/$id'
    | '/api/public/refresh-events'
    | '/api/public/sweep-events'
  id:
    | '__root__'
    | '/'
    | '/answer'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/reset-password'
    | '/settings'
    | '/alert/$id'
    | '/event/$id'
    | '/api/public/refresh-events'
    | '/api/public/sweep-events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswerRoute: typeof AnswerRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  AlertIdRoute: typeof AlertIdRoute
  EventIdRoute: typeof EventIdRoute
  ApiPublicRefreshEventsRoute: typeof ApiPublicRefreshEventsRoute
  ApiPublicSweepEventsRoute: typeof ApiPublicSweepEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer': {
      id: '/answer'
      path: '/answer'
      fullPath: '/answer'
      preLoaderRoute: typeof AnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/$id': {
      id: '/alert/$id'
      path: '/alert/$id'
      fullPath: '/alert/$id'
      preLoaderRoute: typeof AlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sweep-events': {
      id: '/api/public/sweep-events'
      path: '/api/public/sweep-events'
      fullPath: '/api/public/sweep-events'
      preLoaderRoute: typeof ApiPublicSweepEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-events': {
      id: '/api/public/refresh-events'
      path: '/api/public/refresh-events'
      fullPath: '/api/public/refresh-events'
      preLoaderRoute: typeof ApiPublicRefreshEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswerRoute: AnswerRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  AlertIdRoute: AlertIdRoute,
  EventIdRoute: EventIdRoute,
  ApiPublicRefreshEventsRoute: ApiPublicRefreshEventsRoute,
  ApiPublicSweepEventsRoute: ApiPublicSweepEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
