/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnswerRouteImport } from './routes/answer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventIdRouteImport } from './routes/event.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerRoute = AnswerRouteImport.update({
  id: '/answer',
  path: '/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/event/$id': typeof EventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/event/$id': typeof EventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/event/$id': typeof EventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/answer'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/settings'
    | '/event/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/answer'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/settings'
    | '/event/$id'
  id:
    | '__root__'
    | '/'
    | '/answer'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/settings'
    | '/event/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswerRoute: typeof AnswerRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  EventIdRoute: typeof EventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer': {
      id: '/answer'
      path: '/answer'
      fullPath: '/answer'
      preLoaderRoute: typeof AnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswerRoute: AnswerRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  EventIdRoute: EventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
