/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AnswerRouteImport } from './routes/answer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AlertIdRouteImport } from './routes/alert.$id'
import { Route as ApiPublicSweepEventsRouteImport } from './routes/api/public/sweep-events'
import { Route as ApiPublicRefreshEventsRouteImport } from './routes/api/public/refresh-events'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerRoute = AnswerRouteImport.update({
  id: '/answer',
  path: '/answer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => ProfileRoute,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const AlertIdRoute = AlertIdRouteImport.update({
  id: '/alert/$id',
  path: '/alert/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSweepEventsRoute = ApiPublicSweepEventsRouteImport.update({
  id: '/api/public/sweep-events',
  path: '/api/public/sweep-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshEventsRoute = ApiPublicRefreshEventsRouteImport.update({
  id: '/api/public/refresh-events',
  path: '/api/public/refresh-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/business': typeof BusinessRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/alert/$id': typeof AlertIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/event/$id': typeof EventIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/public/refresh-events': typeof ApiPublicRefreshEventsRoute
  '/api/public/sweep-events': typeof ApiPublicSweepEventsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/business': typeof BusinessRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/alert/$id': typeof AlertIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/event/$id': typeof EventIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/public/refresh-events': typeof ApiPublicRefreshEventsRoute
  '/api/public/sweep-events': typeof ApiPublicSweepEventsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answer': typeof AnswerRoute
  '/business': typeof BusinessRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/alert/$id': typeof AlertIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/event/$id': typeof EventIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/public/refresh-events': typeof ApiPublicRefreshEventsRoute
  '/api/public/sweep-events': typeof ApiPublicSweepEventsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/answer'
    | '/business'
    | '/checkout'
    | '/company'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/alert/$id'
    | '/checkout/return'
    | '/event/$id'
    | '/profile/$username'
    | '/api/public/refresh-events'
    | '/api/public/sweep-events'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/answer'
    | '/business'
    | '/checkout'
    | '/company'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/alert/$id'
    | '/checkout/return'
    | '/event/$id'
    | '/profile/$username'
    | '/api/public/refresh-events'
    | '/api/public/sweep-events'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/answer'
    | '/business'
    | '/checkout'
    | '/company'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/alert/$id'
    | '/checkout/return'
    | '/event/$id'
    | '/profile/$username'
    | '/api/public/refresh-events'
    | '/api/public/sweep-events'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswerRoute: typeof AnswerRoute
  BusinessRoute: typeof BusinessRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  AlertIdRoute: typeof AlertIdRoute
  EventIdRoute: typeof EventIdRoute
  ApiPublicRefreshEventsRoute: typeof ApiPublicRefreshEventsRoute
  ApiPublicSweepEventsRoute: typeof ApiPublicSweepEventsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer': {
      id: '/answer'
      path: '/answer'
      fullPath: '/answer'
      preLoaderRoute: typeof AnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/alert/$id': {
      id: '/alert/$id'
      path: '/alert/$id'
      fullPath: '/alert/$id'
      preLoaderRoute: typeof AlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sweep-events': {
      id: '/api/public/sweep-events'
      path: '/api/public/sweep-events'
      fullPath: '/api/public/sweep-events'
      preLoaderRoute: typeof ApiPublicSweepEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-events': {
      id: '/api/public/refresh-events'
      path: '/api/public/refresh-events'
      fullPath: '/api/public/refresh-events'
      preLoaderRoute: typeof ApiPublicRefreshEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ProfileRouteChildren {
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUsernameRoute: ProfileUsernameRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswerRoute: AnswerRoute,
  BusinessRoute: BusinessRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  AlertIdRoute: AlertIdRoute,
  EventIdRoute: EventIdRoute,
  ApiPublicRefreshEventsRoute: ApiPublicRefreshEventsRoute,
  ApiPublicSweepEventsRoute: ApiPublicSweepEventsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
